- name: Update the system (ubuntu/debian)
  apt:
    upgrade: safe
    update_cache: yes

- name: Install requirements (ubuntu/debian)
  apt:
    name:
      - curl
      - fail2ban
      - python3-pip
      - nfs-common
    state: latest
