- name: Install DNF, repos IUS & EPEL (centos/redhat)
  yum:
    name:
      - dnf
      #- python-dnf
      #- https://repo.ius.io/ius-release-el7.rpm
      #- https://repo.ius.io/ius-release-el8.rpm # no repo for cos8 
      # Many IUS packages have dependencies from the EPEL repository
      - epel-release
      #- https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: latest

- name: Update the system (centos/redhat)
  dnf:
    name: '*'
    state: latest
    update_cache: yes

- name: Install requirements (centos/redhat)
  dnf:
    name: 
      - fail2ban
      - htop
      - python3-pip
      - vim
    state: latest

- name: Fail2ban default configuration for sshd (centos/redhat)
  blockinfile:
    path: /etc/fail2ban/jail.local
    create : yes
    state : present
    block: |
      [DEFAULT]
      # Ban hosts for one hour:
      bantime = 3600
      # Override /etc/fail2ban/jail.d/00-firewalld.conf:
      banaction = iptables-multiport
      [sshd]
      enabled = true
