- name: Install requirements
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common
    state: latest

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Add Docker's repository into sources list
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker engine community
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: Install Docker compose v2
  apt:
    name:
      - docker-compose-plugin
    state: latest
  when: ansible_facts['distribution_release']|lower != 'stretch'
  # No package for Debian-9 Stretch
