# OS specific tasks
- name: Install Docker for Debian/Ubuntu
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Install Docker for RedHat/CentOS/Rocky
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

# Generic tasks
- name: Enable Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add default user to Docker's group
  user:
    name: "{{ ansible_distribution | lower }}"
    groups: docker
    append: yes

- name: Install docker-compose
  pip:
    name: 
      - docker-compose
    executable: pip3
    state: latest
